dist: bionic
language: php
sudo: false
cache:
    directories:
        - .phpunit
        - $HOME/.composer/cache/files

env:
    global:
        - PHPUNIT_FLAGS="-v"

matrix:
    fast_finish: true
    include:
        # Minimum supported dependencies with the latest and oldest PHP version
        - php: 7.4
          env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest" SYMFONY_DEPRECATIONS_HELPER="max[self]=0"

        # Test the latest stable release
        - php: 7.4
          env: COVERAGE=true PHPUNIT_FLAGS="-v --coverage-text"

        # Latest commit to master
        - php: 7.4
          env: STABILITY="dev"

    allow_failures:
        - env: STABILITY="dev"

before_install:
    - if [[ $COVERAGE != true ]]; then phpenv config-rm xdebug.ini || true; fi
    - if ! [ -z "$STABILITY" ]; then composer config minimum-stability ${STABILITY}; fi;
    - if ! [ -v "$DEPENDENCIES" ]; then composer require --no-update ${DEPENDENCIES}; fi;

install:
    - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction
    - ./vendor/bin/simple-phpunit install

script:
    - composer validate --strict --no-check-lock
    - ./vendor/bin/simple-phpunit $PHPUNIT_FLAGS
    - ./vendor/bin/phpstan analyse
